version: '3.9'

services:
  api:
    build: 
      context: .
      args:
        - DEV=true
    command: >
      sh -c "alembic upgrade head
             uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - HASH_ALGORITHM=${HASH_ALGORITHM}
      - SECRET_KEY=${SECRET_KEY}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - PROJECT_NAME=${PROJECT_NAME}
    depends_on:
      - db
      
  celery:
    build: .
    command: celery -A core.celery worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A core.celery beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  dev-db-data: